### ISSUE TITLE
Getting a white/black screen when launching

### ISSUE THREAD

**Issue by vinukn335** [TechnoPrashant/Sizer#22]
Getting a white/black screen when launching in example and using in the project,  I don't know this a bug or not.

**Comment by haizadvnet** [comment]
Hi, mine got black screen as well. Suspect issue is "LateError (LateInitializationError: Field 'height' has not been initialized.)". Can you run the apps in debug mode?

**Comment by vinukn335** [comment]
> Hi, mine got black screen as well. Suspect issue is "LateError (LateInitializationError: Field 'height' has not been initialized.)". Can you run the apps in debug mode?

Yes

**Comment by abdimussa87** [comment]
any updates on this??

**Comment by Am607** [comment]
i got the same error ; any update on it;

**Comment by heshaShawky** [comment]
> i got the same error ; any update on it;

do you found a solution for this, I am getting the same issue

**Comment by Am607** [comment]
not yet , but image removed sizer package and used mediaquery ,
