### ISSUE TITLE
ReadMe not up to date

### ISSUE THREAD

**Issue by nietsmmar** [TechnoPrashant/Sizer#23]
Just wanted to inform, that in the readme it says `Wrap MaterialApp with ResponsiveSizer widget` but actually it is called `Sizer` now. Took me some time to realize. Maybe it helps others if this is fixed. Cheers and thanks for this cool lib!

**Comment by calvintam236** [comment]
PR #20 was opened weeks ago but it is still not merged.

**Comment by Altereyo** [comment]
Still not fixed
Thanks @nietsmmar

**Comment by Mitchel-jf** [comment]
Please can you merge the PR #20 ? thanks a bunch

**Comment by kaustuv-praz** [comment]
fix this ASAP.

**Comment by clemsciences** [comment]
What a waste of time. Publishing a package for Flutter and not maintaining it is a shame.

**Comment by nietsmmar** [comment]
> What a waste of time. Publishing a package for Flutter and not maintaining it is a shame.

@clemsciences 
this is still an open source project. Just be grateful that you can use it for free. How do people get an attitude like yours?

**Comment by clemsciences** [comment]
> > What a waste of time. Publishing a package for Flutter and not maintaining it is a shame.
> 
> @clemsciences this is still an open source project. Just be grateful that you can use it for free. How do people get an attitude like yours?

I'm a big fan of open source projects and I also contribute a lot.

The thing is that there are pull requests made by the community to fix mistakes and the maintainer has just disappeared. See #20 to realise that many people wasted their time (you included). An open source project can be given access to other people if one has no time (or whatever the reason is) to maintain it.

**Comment by keezysilencer** [comment]
> > > What a waste of time. Publishing a package for Flutter and not maintaining it is a shame.
> > 
> > 
> > @clemsciences this is still an open source project. Just be grateful that you can use it for free. How do people get an attitude like yours?
> 
> I'm a big fan of open source projects and I also contribute a lot.
> 
> The thing is that there are pull requests made by the community to fix mistakes and the maintainer has just disappeared. See #20 to realise that many people wasted their time (you included). An open source project can be given access to other people if one has no time (or whatever the reason is) to maintain it.

@clemsciences this package is dead. Try the forked ones https://pub.dev/packages/responsive_sizer
