### ISSUE TITLE
LateInitializationError

### ISSUE THREAD

**Issue by Djihanegh** [TechnoPrashant/Sizer#25]
Hello, i'm starting to use Sizer, thank for for this plugin, but im having an issue though, i tried to make my Text widget like this : 

``` dart
 Text(
                                      "Ajouter au panier",
                                      style: TextStyle(
                                          color: Colors.white, fontSize: 20.sp),
                                    ),

```

In order to make the fontSize responsive, but i got this error : 

``LateInitializationError: Field 'width' has not been initialized.``

What's the problem with that ?
Thank you in advance.

**Comment by Yogesh-333** [comment]
Iam also facing same issue any help

**Comment by ryanrahmans26** [comment]
![screenshot-1625639674194](https://user-images.githubusercontent.com/58876269/124711332-25c0a480-df28-11eb-9bf1-f910f18e7f32.png)

Same

i think i want to go back use version 1

**Comment by zamizayn** [comment]
did anyone solved it?
