### ISSUE TITLE
S20+ is recognized as a tablet

### ISSUE THREAD

**Issue by Fhyrel** [TechnoPrashant/Sizer#28]
As I already wrote in title Samsung S20+ is recognised as a tablet. It shouldn't and it makes harder to benefit from this package.

**Comment by kppanchal21** [comment]
Correct there is an issue in code.

![image](https://user-images.githubusercontent.com/6183929/183066926-98f8dd48-902e-41f7-be65-bdae25481dca.png)

The width is already being assigned with the height, in case of landscape mode. And while checking for device type, the code checks for height again, in case of landscape. It should check for width instead. Or just need to remove the condition which is checking for orientation.
