### ISSUE TITLE
Error Initiaalazed late in flutter 2.5 version and sizer 2.0.15

### ISSUE THREAD

**Issue by nurdin442d** [TechnoPrashant/Sizer#39]
I'm using flutter version 2.5 and sizer version 2.0.15. then an error like this appears. can anyone provide a solution. please help me
![image](https://user-images.githubusercontent.com/60811755/144813795-afa8785c-1671-4a1c-b21f-1670069dbef3.png)
![image](https://user-images.githubusercontent.com/60811755/144813845-78d61ebe-d2b9-47c8-a7cf-39689f94a938.png)

**Comment by LoritoTiago** [comment]
Adicione essa linha no seu main
SizerUtil.setScreenSize(restrições, orientação);

**Comment by LoritoTiago** [comment]
![ Captura de Tela 2021-12-07 às 16 16 07](https://user-images.githubusercontent.com/58330997/145055733-4c588d7e-2af9-4477-a422-bc4fe37b5930.png)

deste jeito

**Comment by KhaledAlshafeey** [comment]
Just wrap the MaterialApp widget with Sizer(Builder: (context, Orientation, DeviceType){
  return MaterialApp();
});
