### ISSUE TITLE
Another LateInitializationError issue even after implementing 'return Sizer'

### ISSUE THREAD

**Issue by Neo490** [TechnoPrashant/Sizer#41]
Hello, I've checked many answers on here regarding this issue but I havent been able to solve it  :<

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Sizer(
      builder: (context, orientation, deviceType){
        return GetMaterialApp(
          navigatorKey: Get.key,
          initialRoute: '/home',
          getPages: [
            GetPage(
              name: '/home',
              page: () => HomePage(),
              binding: HomeBinding(),
            ),
          ],
        );
      },
    );
  }
}

which is run on Main with

void main() {
  runApp(const MyApp());
}

Any help is very appreciated, Im looking forward to use this plugin :D

**Comment by jsdaniell** [comment]
Also facing this problem, some solution?

**Comment by ali262883** [comment]
In your main function try adding these lines:
`WidgetsFlutterBinding.ensureInitialized();
  await Future.delayed(const Duration(milliseconds: 200));`
