### ISSUE TITLE
Unable to wrap MaterialApp with ResponsiveSizer

### ISSUE THREAD

**Issue by rehanhamayun** [TechnoPrashant/Sizer#43]
Have a look at it, I have already installed sizer package carefully.

**Comment by nietsmmar** [comment]
Please check this issue https://github.com/TechnoUrmish/Sizer/issues/23

You need to use `Sizer` not `ResponsiveSizer`

**Comment by Narven** [comment]
Please check https://github.com/TechnoUrmish/Sizer/issues/57
