### ISSUE TITLE
LateInitializationError: Field 'width' has not been initialized.

### ISSUE THREAD

**Issue by FrankBenicio** [TechnoPrashant/Sizer#49]
```
Text( 
    "Adress"
    , style: TextStyle(  fontSize: 16.sp )
```

The following LateError was thrown building Widget(dirty, dependencies: [MediaQuery]):
LateInitializationError: Field 'width' has not been initialized.

**Comment by GrrMoura** [comment]
work for me...

ResponsiveSizer(
      builder: (context, orientation, deviceType) {
        return MaterialApp();
      }
 )

**Comment by Narven** [comment]
https://github.com/TechnoUrmish/Sizer/issues/57
