### ISSUE TITLE
Make width and height follow orientation properly

### ISSUE THREAD

**Issue by llucax** [TechnoPrashant/Sizer#5]
Hi, I'm starting to use Sizer and it is great. I'm having an issue though, when trying to support both landscape and portrait orientation, things gets messy, as for some reason Sizer is swapping the width and height when in landscape (for example `MediaQuery.of(context).size` is `Size(668.0, 360.0)` (so width: 668, height: 360) but `100.w` is `360.0` and `100.0.h` is `668.0` (again, when orientation is `Orientation.landscape`, here both `SizerUtil` and `MediaQuery` match).

I notice this is even mentioned in the README, that you should swap width and height based on the orientation, so I guess there is a reason for this, but I can't figure out how to make sense of it. At lease when using the automatic orientation changed by the device.

Am I missing something or is this a bug?

**Comment by begandroide** [comment]
Hi, I'm facing same issue, @llucax what you did for this?

**Comment by llucax** [comment]
I switched to `flutter_screenutil`.

**Comment by begandroide** [comment]
Thank you!!

**Comment by tibfox** [comment]
> Repository owner deleted a comment from llucax on 21 Apr 

why? I miss the response

**Comment by tibfox** [comment]
for everyone having the same issue and wondering why this repo is not maintained anymore for so long: 
take the fork and enjoy! https://pub.dev/packages/responsive_sizer

**Comment by llucax** [comment]
OK, this is really stupid, I just mentioned another package doing the same that worked for me. If a maintainer does. I will never ever use any package for a maintainer that does something like this.

**Comment by llucax** [comment]
It was https://pub.dev/packages/flutter_screenutil BTW.
