### ISSUE TITLE
Blank White Page with GetMaterialApp

### ISSUE THREAD

**Issue by rjkolli7** [TechnoPrashant/Sizer#50]
When using Sizer package along with Getx package. Sizer is not working it showing Empty white screen.

> This is how Sizer is applied to GetMaterialApp widget.

`GetBuilder<ThemeController>(builder: (themeController) {
      return Sizer(builder: (context, orientation, deviceType) {
        return GetMaterialApp(
          debugShowCheckedModeBanner: false,
          enableLog: true,
          logWriterCallback: Logger.write,
          title: StringHelper.appTitle,
          theme: themeController.getTheme(),
          initialRoute: GetPlatform.isMobile
              ? Routes.splash
              : isLogin
                  ? Routes.home
                  : Routes.auth,
          getPages: AppPages.routes,
        );
      });
    });`

There is no error log to provide.

**Comment by Am607** [comment]
I am also using sizer with bloc all and it also giving white screen error in release mode did you fix this issue?

**Comment by boris1690** [comment]
Solution other library https://pub.dev/packages/responsive_sizer/install
