### ISSUE TITLE
LateError (LateInitializationError: Field 'width' has not been initialized.)

### ISSUE THREAD

**Issue by Abolfazl-MI** [TechnoPrashant/Sizer#57]
hello devs ,I just had add to sizer to my project and I use it in my code and when I run 
I face this issue
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
sizer: ^2.0.15 version

**Comment by Narven** [comment]
I also found that issue:

according to https://pub.dev/documentation/sizer/latest/ I think are suppose to wrap MaterialApp like this:

```dart
    ResponsiveSizer(
      builder: (context, orientation, deviceType) {
        return MaterialApp();
      }
 )
```

But `ResponsiveSizer` does not exist or is recognized anywhere... after importing sizer.

**Comment by Narven** [comment]
According to this other reported issue: https://github.com/TechnoUrmish/Sizer/issues/52

You are to wrap with `Sizer` NOT  `ResponsiveSizer` 

So I'm assuming is:

```
Sizer(
      builder: (context, orientation, deviceType) {
        return MaterialApp();
      }
 )
```

**Comment by Narven** [comment]
Looks like there is a PR already for it https://github.com/TechnoUrmish/Sizer/pull/42/files

But it looks like this is a dead project.
