### ISSUE TITLE
Is this project alive or not active?

### ISSUE THREAD

**Issue by hemangjoshi37a** [TechnoPrashant/Sizer#63]
There are no activities from long period of time . I am going to use this for my project but before that I want to make sure that this project is not scrapped .

Thank you.

**Comment by jinosh05** [comment]
Take a look at https://pub.dev/packages/sizer2 where I have updated the code to latest version

**Comment by fisforfaheem** [comment]
please also mention i nversion 1 or rmeove it

**Comment by jinosh05** [comment]
The package was now renamed to sizer_pro.
Thanks for letting me know
