### ISSUE TITLE
The method 'ResponsiveSizer' isn't defined for the type 'MyApp

### ISSUE THREAD

**Issue by Ariwizzy** [TechnoPrashant/Sizer#69]
<img width="343" alt="Screenshot 2023-08-04 at 14 13 33" src="https://github.com/TechnoUrmish/Sizer/assets/52456977/eda56cff-e95a-4115-9f19-363faecbd55a">
after adding the package to the file still not working

**Comment by NaqibAli** [comment]
same in here

**Comment by Ariwizzy** [comment]
> same in here
there is a change in their code I guess. I fixed this by changing the ResponsiveSizer to "Sizer()"
<img width="861" alt="Screenshot 2023-08-10 at 06 59 25" src="https://github.com/TechnoUrmish/Sizer/assets/52456977/817dc02b-44df-42f1-a224-f7fe5ef5370c">

**Comment by krisrandall** [comment]
There are 6 different PRs that have fixed this typo in the documentation : https://github.com/TechnoUrmish/Sizer/pulls
