### ISSUE TITLE
Sizer not working with routes

### ISSUE THREAD

**Issue by fof-fa** [TechnoPrashant/Sizer#72]
import 'package:flutter/material.dart';
import 'greeting/screens_greeting.dart';
import 'package:sizer/sizer.dart';

void main() {
  runApp(Sizer(builder: (context, orientation, deviceType) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: '/',
      routes: {
        '/': (context) => const Main(),
        '/first_greeting': (context) => const FirstGreeting(),
        '/second_greeting': (context) => const SecondGreeting(),
        '/third_greeting': (context) => const ThirdGreeting(),
        '/fourth_greeting': (context) => const FourthGreeting(),
        '/fifth_greeting': (context) => const FifthGreeting(),
        '/sixth_greeting': (context) => const SixthGreeting(),
      },
    );
  }));
}

How fix it?

**Comment by ty1135** [comment]
any update ?

**Comment by TechnoPrashant** [comment]
Fixed in Version 3.0.3
