### ISSUE TITLE
Problem importing Sizer

### ISSUE THREAD

**Issue by CadisRaziel** [TechnoPrashant/Sizer#79]
I have my dart SDK at version: 3.3.2, and my flutter at version 3.19.4 and devTools at version 2.31.1, I'm trying to use Sizer at version 3.0.0 and it's accepted in my app but when I import it into the main
``` 
return Sizer (builder: (context, orientation, screenType) {
      return MaterialApp(
        navigatorKey: NavigationService.navigatorKey,
        localizationsDelegates: const [
```
It has a problem not finding `Sizer` in the dependencies....
Has there been a change in the class? Is there another way to call Sizer?

I did a test and put it in version `2.0.15` in this version it can already find the package to perform the import, so I was in doubt if there was any change at the time of calling this class in my `main`.

Eu tento realizar o import manual `import 'package:sizer/sizer.dart';` porem tenho o seguinte alerta

Unused import: `package:sizer/sizer.dart`. Try removing the import directive

**Comment by RMatushkin** [comment]
Use `ResponsiveSizer`. README is outdated, unfortunately.

**Comment by CadisRaziel** [comment]
@RMatushkin the `ResponsiveSizer` package ?

**Comment by RMatushkin** [comment]
> @RMatushkin the `ResponsiveSizer` package ?

No, of course not. Use widget ResponsiveSizer instead of Sizer from `import 'package:sizer/sizer.dart';`

**Comment by CadisRaziel** [comment]
Ok thx

**Comment by Nisa-fatima369** [comment]
I have having the same issue.. then 2.0.14 was suitable from last day ..but now reading this issue I have just changed the widget with latest version.
