### ISSUE TITLE
Versions 3 and up use the Responsive Sizer widget.

### ISSUE THREAD

**Issue by benjaminhorner** [TechnoPrashant/Sizer#80]
Install version 2.
Upgrade to version 3+ 

The package breaks and the Sizer widget is gone.
The content of the widget.dart file is identical to that of the Responsive Sizer package.

https://github.com/CoderUni/responsive_sizer/blob/main/lib/src/widget.dart
https://github.com/TechnoPrashant/Sizer/blob/master/lib/widget.dart

**Comment by benjaminhorner** [comment]
> I was facing the same issue, but after reading the code, I realized that you need to wrap `MaterialApp` with a `ResponsiveSizer` instead of `Sizer`. After doing that my app works fine.
> 
> ![image](https://private-user-images.githubusercontent.com/79023856/361901615-a9855d8c-2efb-4d34-8641-af370d8540f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzYyOTcsIm5iZiI6MTcyNDgzNTk5NywicGF0aCI6Ii83OTAyMzg1Ni8zNjE5MDE2MTUtYTk4NTVkOGMtMmVmYi00ZDM0LTg2NDEtYWYzNzBkODU0MGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA5MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNTlmNDcyM2QzODYxZmExYmI1YTE3NGY2ZWM3OWQ4MWVjNDM3ZmRhNGZhZDdjMTRiOTY2NTdkN2E4YTJkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.arhJBfr7BZNZUNS1ptuF9EzBXhlq0kVkTc0vNJCVIzA)
> 
> I suspect that the documentation hasn't been updated yet.

Yeah. I did try that after reading the code but once that is done, all .w .sp etc do NOT work anymore and I am left with the ResponsoveSizer package features. If you compare V2 to V3, you will notice there are LOTS of changes.

**Comment by ilyasarafathemvigo** [comment]
facing same issue

**Comment by AG-Akash09** [comment]
We are encountering the same issue when manually updating the Sizer to ResponsiveSizer, which causes the entire screen layout to break. Do you have any suggestions for resolving this?

**Comment by mvtmm** [comment]
Facing the same issue. My whole Layout is broken.

**Comment by Berker-Sen** [comment]
Our layout is broken as well, .sp and .h values (probably others as well) are calculated much smaller then they are suppose to be. Please keep the calculations same as before. Thanks.

**Comment by TechnoPrashant** [comment]
Change ResponsiveSizer to Sizer in Version 3.0.4
