### ISSUE TITLE
The method 'Sizer' isn't defined

### ISSUE THREAD

**Issue by demanhamed** [TechnoPrashant/Sizer#85]
# Installation

Add sizer to pubspec.yaml:
dependencies:
  sizer: ^3.0.3

# Usage

```import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';

class AboutView extends StatelessWidget {
  const AboutView({super.key});

  @override
  Widget build(BuildContext context) {
    return Sizer(
      builder: (context, orientation, screenType) {
        return const MaterialApp(
          home: Text('Home View'),
        );
      },
    );
  }
}
```

# Expectation

Since every step goes smoothly, it should work fine.

# Instead

The method 'Sizer' isn't defined for the type 'AboutView'.
Try correcting the name to the name of an existing method, or defining a method named 'Sizer'.dartundefined_method
Type: InvalidType

**Comment by AmrTawfek** [comment]
I think we can use it with latest version (sizer: ^3.0.3) like this:

ResponsiveSizer( 
  builder: (context, orientation, screenType) {
    return MaterialApp(
      home: HomePage(),
    );
  },
);

**Comment by AmrTawfek** [comment]
I think we can use it with latest version (sizer: ^3.0.3) like this:
`ResponsiveSizer(
builder: (context, orientation, screenType) {
return MaterialApp(
home: HomePage(),
);});`

**Comment by demanhamed** [comment]
Uh, I see, unlike what is mentioned in the documentation.
