### ISSUE TITLE
ResponsiveSizer re-builds all routes on open/close keyboard

### ISSUE THREAD

**Issue by stefanmusat** [TechnoPrashant/Sizer#86]
After upgrading to latest version, I've wrapped the MaterialApp.router with ResponsiveSizer and when I have a TextField or TextFormField, on opening or closing the keyboard, all build methods till that widget that contains the text fields are re called.

**Comment by Jay-0th** [comment]
@stefanmusat 
it seems to be an isse with MediaQuery.
https://github.com/flutter/flutter/issues/135400#issuecomment-1734826457
based on this 
if you just change these two values
    final viewPadding = MediaQuery.viewPaddingOf(context);
    pixelRatio = MediaQuery.devicePixelRatioOf(context);
  in utils.dart file this problem is fixed

**Comment by TechnoPrashant** [comment]
Change ResponsiveSizer to Sizer in Version 3.0.4
