### ISSUE TITLE
Sizer's SP extension is not properly working

### ISSUE THREAD

**Issue by plchekspend** [TechnoPrashant/Sizer#87]
@TechnoPrashant @TechnoUrmish 
Sizer's SP extension is not properly working after update to the latest version 3.0.4, this will occurs after 2.0.14 version.
here is the screen shot of my app after updating to the latest version.
![Screenshot_1727845284](https://github.com/user-attachments/assets/d40f1825-3357-478b-85a8-4e3444e7ba68)
Please test once and provide the feedback also provide the solution.
Also DP extension is removed then please update the documentation also.
Thanks..

**Comment by TechnoPrashant** [comment]
@plchekspend  Doc already updated

**Comment by plchekspend** [comment]
@TechnoPrashant  i'm asking about SP extension it's not working properly when it's used in text sizes, size of that text is getting smaller. Please check with latest version from your side. Thanks..

**Comment by plchekspend** [comment]
@TechnoPrashant  Any update so far? regarding sp extension?
if above is not fixed then most of the developers stops using this package, please try to understand, what changes causes this behaviour.

**Comment by TechnoPrashant** [comment]
@plchekspend  sorry for the inconvenience but have to change from your side based on the new implementation.

**Comment by plchekspend** [comment]
@TechnoPrashant  I already change code from my side with latest package version after doing that this SP extension issue occurs.

**Comment by TechnoPrashant** [comment]
@plchekspend  Can you please send code in my email I will review and update you asap.
