### ISSUE TITLE
Dependencies Update Request.

### ISSUE THREAD

**Issue by Andrious** [TechnoPrashant/Sizer#88]
Great app!

However, in 3.04, you changed name back to 'Sizer' from 'ResponsiveSizer.'

I can't use Sizer: ^3.0.4 as it's incompatible with flutter_lints: ^5.0.0

I can only use Sizer: 3.0.0

Please, would you update pubspec.yaml  with either:

dependencies:
  lints: ^5.0.0

          or  

dev_dependencies:
  flutter_lints: ^5.0.0

Regards,

Greg

**Comment by Abion47** [comment]
The real issue here is that `lints` is a development tool, not a package that sizer requires to function. As such, it should be under dev_dependencies, not dependencies, so it doesn't cause these unnecessary conflicts with downstream packages and projects.
