### ISSUE TITLE
sizer SP extension ruined my view

### ISSUE THREAD

**Issue by AnkitFlutterDev** [TechnoPrashant/Sizer#89]
after upgrading
sizer: ^2.0.15 to ^3.0.4
my all TextStyle which is depend on .sp got to smaller,does i need to changed my all font sizes or use other package which gives regular updates

**Comment by TechnoPrashant** [comment]
@AnkitFlutterDev  Based on a new update of the package have to change in your code. sorry for the inconvenience we are doing our best to make it easy for the developer.
