### ISSUE TITLE
DP has some absurd values

### ISSUE THREAD

**Issue by Boba-Krett** [TechnoPrashant/Sizer#92]
I tried to use .dp for some image and font sizes, and I got overflows in app. I decided to print them in console and found out weird thing:

I/flutter (22567): 15.dp: 43200.0
I/flutter (22567): 15.sp: 11.91889974779319

and my prints:

print("15.dp: ${15.dp}");
    print("15.sp: ${15.sp}");
    
    I am sing sizer: ^3.0.3

**Comment by TechnoPrashant** [comment]
Please read FAQ
